// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkeojynclitmupctuygk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZW9qeW5jbGl0bXVwY3R1eWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDU1ODMsImV4cCI6MjA1NzM4MTU4M30.XsBak2F3WYm-sYu3UW7gVMDVBiEbUq4335cFqa9CadI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);